export const ADMIN_ACTIONS = [
  "LOGIN",
  "LOGOUT",
  "CATEGORY_CREATE",
  "CATEGORY_UPDATE",
  "CATEGORY_DELETE",
  "MENU_CREATE",
  "MENU_UPDATE",
  "MENU_DELETE",
  "SET_COMPONENT_ADD",
  "SET_COMPONENT_REMOVE",
  "INVENTORY_UPDATE",
  "ORDER_CANCEL",
];
